language: csharp
mono:
    - 4.2.0
    - 4.0.0
    - 3.12.0

before_install:
    - export CC=gcc
    - sudo apt-get install libevent-dev

script:
    - ./autogen.sh --prefix=/usr
    - make
    - sudo make install

